- name: cli-plugin-submit
  referenceId: 51CB71JE
  build:
    provider: dkcicd
    pipelines:
      - name: techdocs-v1
        parameters:
          entityReference: default/component/cli-plugin-submit
          sourceDir: ./
        when:
          - event: push
            source: branch
            regex: master
            path:
              - "docs/**"
              - README.md
              - .vtex/deployment.yaml
      - name: node-ci-v2
        parameters:
          sonarProjectName: cli-plugin-submit
          gitBaseBranchName: "master"
          nodeVersion: 20-bookworm
          nodeCommands:
            - test -- --passWithNoTests --coverage
        runtime:
          architecture: amd64
        when:
          - event: pull_request
            source: branch
          - event: push
            source: branch
            regex: master

      - name: npm-publish-v1
        parameters:
          nodeVersion: "20-bookworm"
          packageManager: yarn
          skipInstall: false
          nodeCommands:
            - build
          publishViaGithubWorkflow: true
          workflowFile: publish-npm.yml
          workflowVersion: '{{ ref_name }}'
        when:
          - event: push
            source: tag
